<?php
return array(
    'General Things' => array(
        'All'           => 1,
        'Abstract'      => 2,
        'Animal related (non-anthro)' => 3,
        'Anime'         => 4,
        'Comics'        => 5,
        'Doodle'        => 6,
        'Fanart'        => 7,
        'Fantasy'       => 8,
        'Human'         => 9,
        'Portraits'     => 10,
        'Scenery'       => 11,
        'Still Life'    => 12,
        'Tutorials'     => 13,
        'Miscellaneous' => 14,

    ),

    'Fetish / Furry specialty' => array(
        'Baby fur'               => 101,
        'Bondage'                => 102,
        'Digimon'                => 103,
        'Fat Furs'               => 104,
        'Fetish Other'           => 105,
        'Fursuit'                => 106,
        'Hyper'                  => 107,
        'Inflation'              => 108,
        'Macro / Micro'          => 109,
        'Muscle'                 => 110,
        'My Little Pony / Brony' => 111,
        'Paw'                    => 112,
        'Pokemon'                => 113,
        'Pregnancy'              => 114,
        'Sonic'                  => 115,
        'Transformation'         => 116,
        'Vore'                   => 117,
        'Water Sports'           => 118,
        'General Furry Art'      => 100,
    ),

    'Music' => array(
        'Techno'      => 201,
        'Trance'      => 202,
        'House'       => 203,
        '90s'         => 204,
        '80s'         => 205,
        '70s'         => 206,
        '60s'         => 207,
        'Pre-60s'     => 208,
        'Classical'   => 209,
        'Game Music'  => 210,
        'Rock'        => 211,
        'Pop'         => 212,
        'Rap'         => 213,
        'Industrial'  => 214,
        'Other Music' => 200,
    )
);