<?php
return array(
    ":-p" => "tongue.png",
    ":cool:" => "cool.png",
    ";-)" => "wink.png",
    ":-o" => "oooh.png",
    ":-)" => "smile.png",
    ":evil:" => "evil.png",
    ":huh:" => "huh.png",
    ":whatever:" => "dunno.png",
    ":angel:" => "angel.png",
    ":badhair:" => "badhairday.png",
    ":lmao:" => "lmao.png",
    ":cd:" => "cd.png",
    ":cry:" => "crying.png",
    ":idunno:" => "dunno.png",
    ":embarrassed:" => "embarrassed.png",
    ":gift:" => "gift.png",
    ":coffee:" => "coffee.png",
    ":love:" => "love.png",
    ":isanerd:" => "nerd.png",
    ":note:" => "note.png",
    ":retard:" => "derp.png",
    ":derp:" => "derp.png",
    ":sarcastic:" => "sarcastic.png",
    ":serious:" => "serious.png",
    ":-(" => "sad.png",
    ":sleepy:" => "sleepy.png",
    ":teeth:" => "teeth.png",
    ":veryhappy:" => "veryhappy.png",
    ":yelling:" => "yelling.png",
    ":zipped:" => "zipped.png",
);